In [74]:
import pandas as pd
import numpy as np
from scipy.stats import t
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt 
from sklearn.metrics import confusion_matrix

def cutWeek(weekNumber, data):
    weekdata = []
    for i in range(weekNumber):
         temp = data[data.Week_Number == i]
         temp = temp.reset_index(drop=True)
         weekdata.append(temp)
    return weekdata

def labelMapping(year, week, label):
    labelMap = {}
    for (y, w, l) in zip(year, week, label):
        key = (y, w)
        value = l
        labelMap[key] = value
    return labelMap

def proficCalculator(data, fund):
    # Week 0 case
    week1Data = data[0]
    week1Label = week1Data.Label[0] # week 0 label

    if week1Label == 1:
        stock = True
        buyPrice = week1Data.Close[0] # week 0 first day price
        sellPrice = week1Data.Close[len(week1Data)-1] # week 0 last day price
    else:
        stock = False
        buyPrice = week1Data.Close[len(week1Data)-1] # week 0 last day price
        sellPrice = week1Data.Close[len(week1Data)-1] # week 0 last day price


    for df in data[1:]:
        nextWeekColor = df.Label[0]
        nextClosePrice = df.Close[len(df)-1]

        # stock + green = no action
        if (stock == True) and (nextWeekColor == 1):
            stock == True # Keep holding the stock
            buyPrice = buyPrice # Buy point stay
            sellPrice = nextClosePrice # Sell point move forward

        # stock + red = sell
        elif (stock == True) and (nextWeekColor == 0):
            r = 1 + (sellPrice - buyPrice) / sellPrice
            fund = fund * r
            buyPrice = nextClosePrice
            sellPrice = nextClosePrice
            stock = False
            
        # money + green = buy stock
        elif (stock == False) and (nextWeekColor == 1):
            buyPrice = buyPrice
            sellPrice = nextClosePrice
            stock = True
        # money + red = no action
        elif (stock == False) and (nextWeekColor == 0):
            buyPrice = nextClosePrice
            sellPrice = nextClosePrice
            stock = False

    # Last withdraw
    r = 1 + (sellPrice - buyPrice) / sellPrice
    fund = fund * r
    return fund

In [75]:
dfLabel = pd.read_csv('./GOOGL_weekly_return_volatility.csv')
year1 = dfLabel[dfLabel.Year == 2019]
year2 = dfLabel[dfLabel.Year == 2020]
year1

Year  Week_Number  mean_return  volatility  label
0   2019            0     0.786333    4.007779      1
1   2019            1    -0.251200    0.782992      0
2   2019            2     0.802600    1.639555      1
3   2019            3    -0.119000    1.783558      0
4   2019            4     0.326400    2.111818      1
5   2019            5    -0.278600    1.825005      0
6   2019            6     0.316400    1.179480      1
7   2019            7    -0.064000    1.158254      0
8   2019            8     0.568400    0.787367      1
9   2019            9     0.029000    0.955047      0
10  2019           10     0.698400    1.297292      1
11  2019           11     0.300600    1.646576      1
12  2019           12    -0.513400    0.543586      1
13  2019           13     0.583800    0.901294      1
14  2019           14     0.186800    0.602807      1
15  2019           15     0.381250    0.235024      1
16  2019           16     0.575200    0.834110      1
17  2019           17    -1.355200    3.810197      0
18  2019           18    -0.369400    0.601934      0
19  2019           19     0.047200    2.642586      0
20  2019           20    -0.517000    1.099986      0
21  2019           21    -0.709500    0.956499      0
22  2019           22    -0.655200    3.259066      0
23  2019           23     0.336200    0.823410      1
24  2019           24     0.710200    0.464354      1
25  2019           25    -0.763000    1.159228      0
26  2019           26     1.132250    0.326705      1
27  2019           27     0.227200    1.052729      1
28  2019           28    -0.240000    0.740639      0
29  2019           29     2.003000    4.306430      1
30  2019           30    -0.797200    0.412161      0
31  2019           31    -0.101400    2.391520      0
32  2019           32    -0.150200    1.817134      0
33  2019           33    -0.423600    1.931863      0
34  2019           34     0.636000    0.937403      1
35  2019           35     0.343250    1.867023      1
36  2019           36     0.554400    0.622955      1
37  2019           37    -0.163600    0.537885      0
38  2019           38    -0.054600    1.487093      0
39  2019           39    -0.234600    1.663302      0
40  2019           40     0.082200    0.992642      1
41  2019           41     0.471400    1.003384      1
42  2019           42     0.319200    0.610083      1
43  2019           43     0.135000    1.557997      0
44  2019           44     0.573200    0.668844      1
45  2019           45     0.376800    1.054349      1
46  2019           46    -0.604600    0.339611      0
47  2019           47     0.202500    0.680642      0
48  2019           48     0.540400    1.101453      1
49  2019           49     0.111600    0.183005      1
50  2019           50     0.066000    0.617278      0
51  2019           51     0.066000    0.880678      0
52  2019           52    -0.563000    0.762261      0

In [76]:
# year1 provide paramieters
yesData = year1[year1.label == 1]
noData = year1[year1.label == 0]

pYes = len(yesData) / (len(year1))
pNo = len(noData) / len(year1)

muF1Yes, sigF1Yes = yesData.mean_return.mean(), yesData.mean_return.std()
muF2Yes, sigF2Yes = yesData.volatility.mean(), yesData.volatility.std()

muF1No, sigF1No = noData.mean_return.mean(), yesData.mean_return.std()
muF2No, sigF2No = noData.volatility.mean(), yesData.volatility.std()

# Predict year 2 label
yTest = year2.label
f1 = year2.mean_return
f2 = year2.volatility



yPredict = []
dfree = 0.5
for (f1Test, f2Test) in zip(f1, f2):


    pF1Yes = t.pdf(x = f1Test, df = dfree, loc = muF1Yes, scale = sigF1Yes) 
    pF2Yes = t.pdf(x = f2Test, df = dfree, loc = muF2Yes, scale = sigF2Yes)

    pF1No = t.pdf(x = f1Test, df = dfree, loc = muF1No, scale = sigF1No)
    pF2No = t.pdf(x = f2Test, df = dfree, loc = muF2No, scale = sigF2No)

    pY = pF1Yes * pF2Yes * pYes
    pN = pF1No * pF2No * pNo

    if pY >= pN:
        yPredict.append(1)
    else:
        yPredict.append(0)

print(accuracy_score(yTest, yPredict))
print(pY, pN)

## Confusion Matrix I choose 
temp = confusion_matrix(yTest, yPredict)
print(temp)

tn = temp[0][0]
fn = temp[1][0]
tp = temp[1][1]
fp = temp[0][1]

tpr = tp / (tp + fn)
tnr = tn / (tn + fp)

print('TPR = {}, TNR = {}'.format(tpr, tnr))




0.7924528301886793
0.020383396835891302 0.030197016380249936
[[19  6]
 [ 5 23]]
TPR = 0.8214285714285714, TNR = 0.76


In [77]:
yPredict = []
dfree = 1

for (f1Test, f2Test) in zip(f1, f2):


    pF1Yes = t.pdf(x = f1Test, df = dfree, loc = muF1Yes, scale = sigF1Yes) 
    pF2Yes = t.pdf(x = f2Test, df = dfree, loc = muF2Yes, scale = sigF2Yes)

    pF1No = t.pdf(x = f1Test, df = dfree, loc = muF1No, scale = sigF1No)
    pF2No = t.pdf(x = f2Test, df = dfree, loc = muF2No, scale = sigF2No)

    pY = pF1Yes * pF2Yes * pYes
    pN = pF1No * pF2No * pNo

    if pY >= pN:
        yPredict.append(1)
    else:
        yPredict.append(0)

print(accuracy_score(yTest, yPredict))
print(pY, pN)

## Confusion Matrix I choose 
temp = confusion_matrix(yTest, yPredict)
print(temp)

tn = temp[0][0]
fn = temp[1][0]
tp = temp[1][1]
fp = temp[0][1]

tpr = tp / (tp + fn)
tnr = tn / (tn + fp)

print('TPR = {}, TNR = {}'.format(tpr, tnr))


0.7924528301886793
0.036566590987857826 0.052524982181426455
[[19  6]
 [ 5 23]]
TPR = 0.8214285714285714, TNR = 0.76


In [78]:

yPredict = []
dfree = 5
for (f1Test, f2Test) in zip(f1, f2):


    pF1Yes = t.pdf(x = f1Test, df = dfree, loc = muF1Yes, scale = sigF1Yes) 
    pF2Yes = t.pdf(x = f2Test, df = dfree, loc = muF2Yes, scale = sigF2Yes)

    pF1No = t.pdf(x = f1Test, df = dfree, loc = muF1No, scale = sigF1No)
    pF2No = t.pdf(x = f2Test, df = dfree, loc = muF2No, scale = sigF2No)

    pY = pF1Yes * pF2Yes * pYes
    pN = pF1No * pF2No * pNo

    if pY >= pN:
        yPredict.append(1)
    else:
        yPredict.append(0)

print(accuracy_score(yTest, yPredict))
print(pY, pN)


## Confusion Matrix I choose 
temp = confusion_matrix(yTest, yPredict)
print(temp)

tn = temp[0][0]
fn = temp[1][0]
tp = temp[1][1]
fp = temp[0][1]

tpr = tp / (tp + fn)
tnr = tn / (tn + fp)

print('TPR = {}, TNR = {}'.format(tpr, tnr))





0.7924528301886793
0.06860962839991763 0.09423087601272048
[[19  6]
 [ 5 23]]
TPR = 0.8214285714285714, TNR = 0.76


In [79]:
# Strategy check
dfDetail = pd.read_csv('./GOOGL_weekly_return_volatility_detailed.csv')
year2Detail = dfDetail[dfDetail.Year == 2020]
year2Detail = year2Detail.reset_index(drop = True)

## Add label to detail
lMap = labelMapping(year2.Year, year2.Week_Number, yPredict)
temp = []
for (y, w) in zip(year2Detail.Year, year2Detail.Week_Number):
    key = (y, w)
    temp.append(lMap[key]) 
year2Detail['Label'] = temp
year2Detail = year2Detail[['Year', 'Week_Number', 'Close', 'Label']]

## Cut goo2020
goo2020Week = cutWeek(53, year2Detail)




## trading 
total = proficCalculator(goo2020Week, 100)
print("Using Label: {}".format(total))

## trding BH
firstWeek = goo2020Week[0]
firstClose = firstWeek.Close[0]

lastWeek = goo2020Week[-1]
lastClose = lastWeek.Close[len(lastWeek)-1]

r = 1 + (lastClose - firstClose) / lastClose
total = 100 * r
print("Buy on first day and Sell on last day: {}".format(total))



Using Label: 239.64550014107087
Buy on first day and Sell on last day: 121.17033527942765
